version: '3.8'

services:
  redis-biblioteca:
    image: redis:7-alpine
    container_name: biblioteca_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: always

volumes:
  redis_data: